apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jerney-kustomize
  namespace: jerney
resources:
- be-deployments.yaml
- fe-deployments.yaml
- db-deployments.yaml

images:
- name: abhishekbakare/jerney-backend
  newName: ghcr.io/user/repo/jerney-backend
  newTag: temporary
- name: abhishekbakare/jerney-backend:latest
  newName: ghcr.io/abhishek-bakare/DevSecOps-Blog/jerney-backend
  newTag: 0eb46b5
- name: abhishekbakare/jerney-frontend
  newName: ghcr.io/user/repo/jerney-frontend
  newTag: temporary
- name: abhishekbakare/jerney-frontend:latest
  newName: ghcr.io/abhishek-bakare/DevSecOps-Blog/jerney-frontend
  newTag: 0eb46b5
- name: postgres
  newName: postgres
  newTag: 16-alpine
