apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jerney-kustomize
  namespace: jerney
resources:
- be-deployments.yaml
- fe-deployments.yaml
- db-deployments.yaml
- be-service.yaml
- be-np.yaml
- db-service.yaml
- fe-service.yaml
- namespace.yaml
- pvc.yaml
- secrets.yaml
- storageclass.yaml

images:
- name: abhishekbakare/jerney-backend
  newName: ghcr.io/user/repo/jerney-backend
  newTag: temporary
- name: abhishekbakare/jerney-backend:latest
  newName: ghcr.io/abhishek-bakare/devsecops-blog/jerney-backend
  newTag: 452c4ed
- name: abhishekbakare/jerney-frontend
  newName: ghcr.io/user/repo/jerney-frontend
  newTag: temporary
- name: abhishekbakare/jerney-frontend:latest
  newName: ghcr.io/abhishek-bakare/devsecops-blog/jerney-frontend
  newTag: 452c4ed
- name: postgres
  newName: postgres
  newTag: 16-alpine
