apiVersion: v1
kind: Secret
metadata:
  name: jerney-db-secrets
  namspace: jerney
  labels:
    app.kubernetes.io/part-of: jerney
type: Opaque
data:
  POSTGRES_USER: amVybmV5X3VzZXI=
  POSTGRES_PASSWORD: eW91cl9wYXNzd29yZF9oZXJl
  POSTGRES_DB: amVybmV5X2Ri

